### PR TITLE
Iniital project scaffold

### PR DESCRIPTION
**Pull request by addisonhernandez**
Here's what I've built out so far:

 - Initialize a new project using vite
 - Add Airbnb style guide (we should tweak this a bit)
 - Add ESLint and Prettier to make formatting easier
 - Add React Router for more flexible endpoints
 - Add a README template from Learn

### CODE REVIEW

**Comment by addisonhernandez** [comment]
I'm putting this here in case anyone wants to take a look.

We'll plan to build out a skeleton file structure tomorrow after we wireframe

**Comment by haleyjung** [comment]
This is great!

**Comment by haleyjung** [comment]
This is great. Thank you for fixing the merge conflict.

**Review by haleyjung — COMMENTED** [review]
Great job fixing the merge conflict.

**Review by haleyjung — APPROVED** [review]
Great job fixing the merge conflict.

**Pull request merged**
