### PR TITLE
Completed Reading Stats

### PR DESCRIPTION
**Pull request by haleyjung**
- HTTP requests are all in place
- Request is hooked up to the logged in user's id
- Added a screen to show when there is no data from a user to render stats
- Removed all the props being passed down to the reading goal widget and cleaned up the code

### CODE REVIEW

**Review by katyfsy — APPROVED** [review]
lgtm!

**Comment by jp-chang** [comment]
nj!

**Review by HuijunLu — APPROVED** [review]
looks good

**Comment by addisonhernandez** [comment]
:fire: :chart_with_upwards_trend: :bar_chart:

**Pull request merged**
