### PR TITLE
Add persistence for user authorization

### PR DESCRIPTION
**Pull request by addisonhernandez**
Preeeeetty sure that we're not supposed to use Local Storage for this, but :shrug:

### CODE REVIEW

**Comment by addisonhernandez** [comment]
I'll put this :point_up: on my tech debt to-do list

**Comment by katyfsy** [comment]
🤩lgtm

**Comment by addisonhernandez** [comment]
[Auth State Persistence](https://trello.com/c/4K5nz3M3/30-auth-state-persistence)

**Review by katyfsy — APPROVED** [review]
🤩LGTM

**Pull request merged**
